name: Publish Release
on:
  release:
    types: ["published"]

jobs:
  nuget-release:
    name: Publish to Modrinth and Github
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build
        run: chmod +x ./gradlew \
          && source tools/quote.sh \
          && sed -i "/mod_version/cmod_version=${{ github.ref }} gradle.properties" \
          && sed -i "/changelog = 'No changelog was specified.'/cchangelog = '${{ github.event.release.body }}'" \
          && ./gradlew build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/libs/

      - name: Upload Artifacts To Github Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: build/libs/*.jar
          token: ${{ secrets.GITHUB_TOKEN }}
          omitBodyDuringUpdate: true # We don't want to update the body of the release.
          omitNameDuringUpdate: true # We don't want to update the name of the release.